RankingSystem.PL/Controllers/ItemController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RankingSystem.BLL.Interfaces;
using RankingSystem.BLL.Repositories;
using RankingSystem.DAL.Models;
using RankingSystem.PL.ViewModels;

namespace RankingSystem.PL.Controllers
{
    [Authorize]
    //[AllowAnonymous] ==> ByDefault
    public class ItemController : Controller
    {
        private readonly IGenericRepository<Item> _itemRepo;
        private readonly IMapper _mapper;

        public ItemController(IGenericRepository<Item> ItemRepo , IMapper mapper)
        {
            _itemRepo = ItemRepo;
            _mapper = mapper;
        }

        //BaseUrl/Item/Index
        //Get All Items
        public async Task<IActionResult> Index()
        {
            var AllItems =await _itemRepo.GetAllAsync();
            var MappedItems = _mapper.Map<IEnumerable<Item>, IEnumerable<ItemViewModel>>(AllItems);
            return View(MappedItems);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ItemViewModel itemVM)
        {
            if (ModelState.IsValid)
            {
                var mappedItem = _mapper.Map<ItemViewModel, Item>(itemVM);
                int Result = _itemRepo.AddAsync(mappedItem);
                if (Result > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(itemVM);
        }

    }
}

RankingSystem.PL/Controllers/RatingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RankingSystem.BLL.Interfaces;
using RankingSystem.DAL.Models;
using RankingSystem.PL.ViewModels;

namespace RankingSystem.PL.Controllers
{
    [Authorize]
    public class RatingController : Controller
    {
        private readonly IGenericRepository<Item> _itemRepo;
        private readonly IGenericRepository<Rating> _RatingRepo;
        private readonly IMapper _mapper;

        public RatingController(IGenericRepository<Item> ItemRepo, IGenericRepository<Rating> RatingRepo,IMapper mapper)
        {
            _itemRepo = ItemRepo;
            _RatingRepo = RatingRepo;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var AllRating = await _RatingRepo.GetAllAsync();
            var MappedRating = _mapper.Map<IEnumerable<Rating>, IEnumerable<RatingViewModel>>(AllRating);
            return View(MappedRating);
        }

        [HttpGet]
        public async Task<IActionResult> Rate(int id)
        {
            var item = await _itemRepo.GetByIdAsync(id);
            var mappedItem = new RatingViewModel()
            {
                ItemId = item.id,
                Item = item,
            };
            return View(mappedItem);
        }

        [HttpPost]
        public async Task<IActionResult> Rate(RatingViewModel RatingVM)
        {
            if (ModelState.IsValid)
            {
                var mappedItem = _mapper.Map<RatingViewModel, Rating>(RatingVM);
                int Result = _RatingRepo.AddAsync(mappedItem);
                if (Result > 0)
                    return RedirectToAction(nameof(Index),nameof(Item));
            }
            return View(RatingVM);
        }



    }
}

RankingSystem.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
    <link href="~/css/authstylesheet.css" rel="stylesheet" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		

		@RenderBody();

		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: true)
</body>
</html>

RankingSystem.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RankingSystem.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RankingSystem.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RankingSystem.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Index">Rates</a>
                        </li>
                        <li class="nav-item ms-auto ">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut <i class="fa-solid ps-2 fa-right-from-bracket"></i></a>
                        </li>
                    </ul>
                </div>
            
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RankingSystem.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>